### ISSUE TITLE
Chart breaks after update

### ISSUE THREAD

**Issue by lenyapugachev** [apexcharts/vue-apexcharts#52]
Hello, below is my code, everything is great, except sometimes after data update chart breaks.
Usually, it is happening when there will be more points than previous set has. After next update chart is again perfect.

```
<ApexCharts type=candlestick :options="chartOptions" :series="series" />

...

export default {
        name: "TerminalCharts",
        props: {
            graph: {
                type: Array,
                default: function() { return []; }
            }
        },
        watch: {
            graph: function(graph) {
                this.series = [{ data: this.graph }];
            }
        },
        components: {
            ApexCharts
        },
        created() {
            this.series = [{ data: this.graph }];
        },
        data () {
            return {
                time: "1m",
                isButtonActive: false,
                chartViewPort: {
                    settings: {
                        candle: true,
                        line: false,
                        depth: false
                    }
                },
                chartOptions: {
                    width: '100%',
                    height: '100%',
                    chart: {
                        id: 'candles',
                        toolbar: {
                          autoSelected: 'pan',
                          show: false
                        },
                        zoom: {
                          enabled: false
                        }
                    },
                    plotOptions: {
                        candlestick: {
                            colors: {
                                upward: '#00B121',
                                downward: '#F65454'
                            }
                        }
                    },
                    grid: {
                        borderColor: '#2B2E39'
                    },
                    xaxis: {
                        type: 'datetime'
                    }
                },
                series: [{ data: [] }]
            }
        }
}
```

Before break:
<img width="1586" alt="2019-02-02 4 00 54" src="https://user-images.githubusercontent.com/2419256/52149584-ca779180-269f-11e9-9928-a320b6b38c7e.png">

After break:
<img width="1408" alt="2019-02-02 4 00 41" src="https://user-images.githubusercontent.com/2419256/52149599-d400f980-269f-11e9-9d0a-99e9596c985d.png">

**Comment by lenyapugachev** [comment]
Thanks @junedchhipa, tomorrow will search for temporary workaround, I tried to update it with empty array before every new update, but that causes a lot of another problems. Maybe you have some thought on temporary solution?

**Comment by junedchhipa** [comment]
Can you please post a working codesandbox example as I cannot easily reproduce by pasting your code? 

Please use this Vue template - https://codesandbox.io/s/pwwz8009n0

**Comment by junedchhipa** [comment]
Ok, I have fixed the error and a patch will be released tomorrow.
Thanks for reporting.

**Comment by lenyapugachev** [comment]
Thanks, I did your change in node_modules and then run yarn again, but problem is still there.
