### ISSUE TITLE
[Vue-ApexCharts] Strange behavior of animation in bar chart 

### ISSUE THREAD

**Issue by vystepanenko** [apexcharts/vue-apexcharts#75]
Hello!
i'm using:
- "vue": "^2.5.17",
- "vue-apexcharts": "^1.1.1",

And I have strange behavior of animation in bar chart  on initial load if series: [ { data: [] } ]  is empty.
At the moment when I initial chart object I do not have data for series and categories
```
 options: {
        chart: {
          id: "isChart",
          dropShadow: { enabled: true, top: 11,  left: 0,  blur: 3,  opacity: 0.5 },
          animations: { enabled: true, easing: "linear", speed: 1500,
            animateGradually: { enabled: true, delay: 1500 },
            dynamicAnimation: { enabled: true, speed: 1500 }
          }
        },
        xaxis: { categories: [] },
      },
      series: [ { name: "s1", data: [] } ]
```
Then I make request to backend and fill series data and categories

```
axios.post("http://mydomain/loadData")
        .then(response => {
          response.data.forEach((element, index) => {
            this.numX.push(index + 1);
            this.numY.push(element.data);
          });
          this.series = [ { data: this.numY }  ];
          this.options = {  xaxis: {  categories: this.numX  }  };
        })
        .catch(error => {
          console.log(error);
        });
```
And on first time animations seems doesn't work and chart appears instantly. If i repeat this action(at this moment series data already filled with some data) animation will work correctly.

This behiavor only with bar chart. 
i try for "area" and "line" charts and animation works correctly even on initial load when series data is emty

**Comment by paolog22** [comment]
+1 same here no animation on chart

**Comment by lvidal1** [comment]
Same bug on:

"apexcharts": "^3.6.8",
"vue-apexcharts": "^1.3.4",

**Comment by paolog22** [comment]
Up for this

**Comment by brunojahel** [comment]
initialize your series array as:
`series: [{data: [0,0,0,0,0,0,0,0]}]` (example for an 8 bar chart)
and it'll work :)

**Comment by mihlek1** [comment]
Same bug here, using mixed column/line chart with no defined indexes

**Comment by amstrad** [comment]
up

**Comment by LACCamacho** [comment]
Same bug in donut charts also

**Comment by TheLinx79** [comment]
Still a bug in 2020.

**Comment by junedchhipa** [comment]
Sorry for the delay here.
Fixed it.
The animation will run fine in the next patch release of core apexcharts (apexcharts@3.15.6)

**Comment by dusanradojcic** [comment]
I still have the same bug with onstart animation of line chart. Has someone fixed tis?

**Comment by prabodhana** [comment]
I  already update to ` apexcharts": "^3.17.1 ` in nuxtjs but still not working

**Comment by tiagolr** [comment]
fixed this by manually calling `this.$refs.chart.updateSeries([val], true)` triggers the animation correctly

**Comment by clowcher** [comment]
same problem with donut chart on `1.5.2`
